### ISSUE TITLE
FastCGI sent in stderr: "Primary script unknown"

### ISSUE THREAD

**Issue by demagu** [yappabe/docker-nginx#7]
This is probably more question than an issue so please bear with me. 

I'm trying your images using `Docker for Mac` in setup visible below with but getting following error: 
```
FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.22.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.5:9000", host: "localhost"
```

My `docker-compose.yml`
```
version: '2'
services:
    app:
        image: yappabe/data
        volumes:
            - .:/var/www/app
            - /vendor
        tty: true

    nginx:
        image: yappabe/nginx:1.9
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - app
        environment:
            DOCUMENT_ROOT: /var/www/app/web
            INDEX_FILE: index.php
            PHP_FPM_SOCKET: php:9000

    mysql:
        image: tutum/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_PASS: dev
            MYSQL_USER: dev
            ON_CREATE_DB: dev

    php:
        image: yappabe/php:7.0
        volumes_from:
            - app
        links:
            - mysql
            - mailcatcher

    mailcatcher:
        image: yappabe/mailcatcher
        ports:
            - 1025:1025
            - 1080:1080
```

Each of the containers work, Mailcatcher works. 

What can be the problem here?
